spring:
  redis:
    host: ${REDIS_URL}
    password: ${REDIS_PASSWORD}
    port: ${REDIS_PORT}
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 2
    ttl:
      refresh_token: 1209600000